# Generated by Django 4.2.1 on 2023-06-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_post_tags_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headerImage_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
