# Generated by Django 4.2.1 on 2023-06-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_headerimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
